# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: make

    - name: Check format
      run: make fmtcheck

    - name: Lint
      run: make lint

    - name: Test
      run: make test
      env: 
        SETHEALTH_KEY: ${{ secrets.SETHEALTH_KEY }}
        SETHEALTH_SECRET: ${{ secrets.SETHEALTH_SECRET }}

    - name: Build
      run: make build
